language: node_js
node_js:
- 4.0
before_install:
- npm install -g gulp-cli
install:
- npm install
after_success:
- chmod +x ./bin/create-release-tag.sh
- "./bin/create-release-tag.sh"
branches:
  except:
  - "/^v/"
deploy:
  provider: heroku
  api_key:
    secure: SY9Y0E/GWmj6wLxeSPJWLz3A69T2iBTeCVlop51+0pbOUMxM8trAqieZbb7ajYAKIQSHhUc/7LqLB1qojr+AqkbFirZRnD9vHo+oxuD7QpxufERfEemW0u6YgcYw6JA43jJKS6i5wuApZW5exrtMCvC6QhP1P0krY5YDBYnaZUys/bZ1u+Ql9Ze4gr7BHXcqM/7ujMohZ5Ox3CEAsiJhayLU8Su/RR0hraeFUA2KNPzAfT8aYSZRWS+LdzX62/BlJuKCMJNd4TeFERlrlGaU29eXncL8k9csRsIy028fDuoOBP19U7r7pEAxaP6UBS6h50qIiOAGNbnB174aLrcLR0v2newRpuJdMK87uHchgM0QMTPaudGh4psHTVauhIRaW+vnwqTijZfgYYJaSx8dUODYhJcNjqxMrvQV1GXdp2n+XVk3Mdz4MIL+F8esUC57Dv6W3g2evHKUpuPGSVrmRFozULFCFcEIftumAOxwLOey21O/g2ARfUhCjEJBR3VvKt6e4dQcwH8mc85fg+5GWjK+gGfAgqtiG9AF1eyiB43SBhbHUugDUCCChQAOdWO0TreSTHPyW3MiPzIbYOZiZmLsQzcxYTdJdzHwTvbh5UwGbpOewWcu+lu3te8cNE6XnY6IjEE4kIPbgqZzBYzInN0K5y5wOw3Sqz7UWfndAvk=
  app: lcc-forms-prototype
  on: master
notifications:
  email: false
sudo: false
