language: node_js
node_js:
- 4.0
before_install:
- npm install -g gulp-cli
install:
- npm install
after_success:
- chmod +x ./bin/create-release-tag.sh
- "./bin/create-release-tag.sh"
branches:
  except:
  - "/^v/"
deploy:
  provider: heroku
  api_key:
    secure: wIsafy0ilLeDc5DpBa2rARhNBd+K6ze01Qp8i4px7ug1HnbID4evzg8Mi2e/Bfod1fIz5Qgwh7pQG6/W7ZXm0AlYGqgVg2ffDGTYElo732JJY53NHPyhvvwpdMZsv2dmrs/0rFfwrSGhuSaeYrfiOHaXX8Jd9oSl0tOfCTN8+SlUcGf5b6MCY8SaEOAkrH2RuCgMYYVT4Cmnso0v7saducWQW1LqNL0GLrf9ZP2yG/Y2P/7gRAhn9gOW8KLtiyPjmJxH2jl03rtrgOockyANhS8HR5vjq1VO29hHI+bRh+gpeIbTcR5d6QkZsCM1PnHjqBezQnSWye1ZBSw8iPZGR6KaXXYeLZNLoPBWuTLrvDWQ72Q+X0DqMksGX0BxHRPhfeKQGMXiwU6uLhrcFI3ohHVvuAn+q5SVlvhbfjHG1v98kGD3kpmEcYV4XQJfG9tAR8cZABr1nIilFhrhV8/sTE7RozVNn92N0lAPbeF4tWKFQRiKMtqc695qdJxmmt9LssQ2bDv+G512AsHsNYPEfdyRw38aYx5X+CKbY6/rsH2X4Cuj1uuX2Pml1JP2mx5g/PAaLfz45giGDmnT3mwpV5p6w39HhLpb0EMeNsdc1NR+dRf8fmrrXHw2FA13nRqjR5NEOs3aGL2TntoJTpRBA5SW/TNOFsymuO080NBcv40=
  app: lcc-forms-prototype
  on: master
notifications:
  email: false
sudo: false
